### ISSUE TITLE
Doesn't work 

### ISSUE THREAD

**Issue by raspin0** [app4deepin/Weather-appimage#2]
![obraz](https://user-images.githubusercontent.com/39202451/180757518-6d4fb253-69de-43bd-a3ac-05f2d945008a.png)

Even though the prompt is showing such information, there are no active instances of weather

**Comment by app4deepin** [comment]
I will look this. ;)

**Comment by app4deepin** [comment]
Try new version : 4.3.1-appimage

**Comment by raspin0** [comment]
Fixed!
